### ISSUE TITLE
ImportError: cannot import name 'DeviceModelSummary' from partially initialized module 'pyavcontrol.library'

### ISSUE THREAD

**Issue by stanislaw2002** [rsnodgrass/hass-mcintosh#1]
Hi,
I'm trying to use your integration but I have some troubles loading it.  Attache below are some related logs.

Thank you for your effort!
Stas

Logger: homeassistant.util.loop
Source: util/loop.py:70
First occurred: 8:18:42 PM (1 occurrences)
Last logged: 8:18:42 PM

Detected blocking call to import_module with args ('custom_components.mcintosh.media_player',) in /usr/src/homeassistant/homeassistant/loader.py, line 1270: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop
...
  File "/config/custom_components/mcintosh/__init__.py", line 14, in <module>
    from pyavcontrol import DeviceClient
  File "/usr/local/lib/python3.12/site-packages/pyavcontrol/__init__.py", line 5, in <module>
    from .library import DeviceModelLibrary
  File "/usr/local/lib/python3.12/site-packages/pyavcontrol/library/__init__.py", line 6, in <module>
    from pyavcontrol.library.yaml_library import YAMLDeviceModelLibrarySync, YAMLDeviceModelLibraryAsync
  File "/usr/local/lib/python3.12/site-packages/pyavcontrol/library/yaml_library.py", line 13, in <module>
    from . import DeviceModelSummary
ImportError: cannot import name 'DeviceModelSummary' from partially initialized module 'pyavcontrol.library' (most likely due to a circular import) (/usr/local/lib/python3.12/site-packages/pyavcontrol/library/__init__.py)

HomeAssistant on RBP5,
Core
2024.5.3
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

**Comment by rsnodgrass** [comment]
The implementation for this has not been completed.  My MX160 was damaged heavily in shipping, so I no longer have a McIntosh device to test with. Hopefully I'll have another in the next few months and can finish this.
